### ISSUE TITLE
Mac OS Wallet private key folder location [Stellar Desktop Client v3.3]

### ISSUE THREAD

**Issue by Twinstar2** [ripplefox/stellarwallet#19]
Hello,

i downloaded the stellar lumen wallet back in 2017, send some lumens to it and then i forgot.
Now the application is not starting anymore on my macbook. So i wonder where the private key folder is so i can export the key and use the latest version.

best regads

**Comment by ripplefox** [comment]
1, Your private key was encrypted in your local file like wallet.txt. You have to find the file first as it was saved somewhere by yourself. 

2, you can use any version of foxlet wallet to open it. If you can not open on your mac, you can open it on a windows PC.
