### ISSUE TITLE
error sending XLM - need help

### ISSUE THREAD

**Issue by pneumee** [ripplefox/stellarwallet#30]
Could use some assistance with trying to send XLM to a Coinbase address. Seems to be a timeout issue, but I'm wondering why this would be happening and how to fix it. Error message is "Request failed with status code 504".

![XLM send error](https://user-images.githubusercontent.com/997002/162856224-1967ccc2-b4db-4999-90cf-23038ac744d5.JPG)

I'm using version 5.1.0 of the Foxlet for Stellar wallet.

**Comment by pneumee** [comment]
I turned off my VPN and it worked. Which is a little strange since I was connected to a VPN server in my local region.

**Comment by pneumee** [comment]
Actually turning the VPN off may have been a coincidence. I had a timeout for one send while off the VPN. 🤷

**Comment by ripplefox** [comment]
You could also download the 6.0 version with the dynamic fee calculation. It would reduce such problem.
