### ISSUE TITLE
Issues with sendings

### ISSUE THREAD

**Issue by ackise** [ripplefox/stellarwallet#4]
I cant send Lumens to another wallet and even after transaction failed system taking fees. Why??

**Comment by juniormayhe** [comment]
this is quite weird. when the account balance is lower than 10 lumens, it says paymentUnderfunded. Every new try will reduce the wallet value by applying a fee of 0.0000100. This system is either not providing enough information on its user interface or this system has some kind of bug. 

这很奇怪。 当帐户余额少于10流明时，显示“ paymentUnderfunded”。 每次尝试将收取0.0000100的费用，从而减少了钱包的价值。 系统在其用户界面上没有提供足够的信息，或者系统存在某种错误。

![](https://i.imgur.com/VhYurYm.png)

**Comment by Dade15** [comment]
i have the same problem with my account, i can not send my stellar to another walllet neither to any other website. there is always an error "txBadAuth"  how can i fix this??

**Comment by ripplefox** [comment]
paymentUnderfunded: you should check your open orders.
txBadAuth may caused by the network.
