### ISSUE TITLE
NAOBTC.COM  BTC/XLM on-ramp / anchor ??

### ISSUE THREAD

**Issue by jimmywhits** [ripplefox/stellarwallet#5]
Hi. Please excuse me in advance for posting on what I realise is a site for developers ( as a software developer for 30+ years myself I realise it's not really the 'done thing', but I'm desperate for help and was advised by the helpful Stellar Community ( via KeyBase) to contact the wallet makers/owners which I see from my wallet is https://github.com/stellarchat/desktop-client, which I believe to now be managed by yourselves?

The problem -

Whilst in my wallet last week I clicked on a link for 'Create Trust Line for BTC' connected with NAOBTC.COM, seconds before pasting my clipboard contents to the SEND to XLM address field. I believe naobtc.com to be a trusted on-ramp for BTC/XLM - I can see communication from Jed McCaleb with them a few years back via Twitter.
I didn't realise that clicking the 'Create Trust' button had changed the contents of my clipboard. This resulted in me sending 30,000 lumens to a wallet I understand believes to NAOBTC.COM, (GBTCBCWLE6YVTR5Y5RRZC36Z37OH22G773HECWEIZTZJSN4WTG3CSOES), instead of the intended recipient who I had sent a successful test transaction to 2 mins before.
I have reached out to the Stellar Community via Keybase and was advised to contact @HanFeng and also @eno. Neither have responded to my requests to help. I have also sent message to the twitter account of NAOBTC.COM but again my requests have fallen on deaf ears to date.  I can see that the wallet has very little activity, and I have also located an article on Github from another individual who had the same problem and stated that 'eno' refunded the payment.

I just need to get a reliable contact at NAOBTC.com to get back to me. I'm hoping the fact that NAOBTC.com are displayed as a 'TRUST' option in my software wallet that somebody within this GITHUB community group will be able to connect me with somebody.

Many thanks for taking the time to digest my response and apologies once again for posting here - I'm just desperate for somebody to help me out.

Thanks
James

**Comment by jimmywhits** [comment]
I managed to get a response from @hanfeng ( KeyBase) who kindly returned the funds to my wallet.  so naobtc.com can certainly be trusted.  Thanks and sorry for any inconvenience caused by posting on this board.

**Comment by ripplefox** [comment]
actually i contact him. you are welcome.



---Original---

**Comment by jimmywhits** [comment]
Thank you for your help – much appreciated.
